# Site
name: 'Loonpic'
description: 'Loonpic Project'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 'https://loonpic.github.io/'
avatar: 'assets/images/sal.jpg'
disqus: 'Photograph / Filmaker'
email: 'lnoering@gmail.com'
timezone: America/Sao_Paulo
lang: en
url: 'https://loonpic.github.io/'


github:
  username: lnoering             # change to your github username

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
# https://raw.githubusercontent.com/lnoering/lnoering.github.io/master
img_cdn: ''

# the avatar on sidebar, support local or CORS resources
avatar: ''


include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]